### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by KenavR** [joshuamorony/ionic-nestjs-websockets-live-chat#1]
Hi,

sorry for creating an issue, but I seem to be unable to figure it out. I converted one of my projects to basically mirror your setup (without ionic) but I get CORS errors when connecting with socket.io. Since your project also runs two different servers (:3000 server and Angular's dev server on :4200), I feel like your project also should have to deal with CORS, but I can't find anything and it just works. According to the [nest.js docs](https://docs.nestjs.com/techniques/security#cors) enabling should be easy, but your project doesn't seem to do that.

Do I miss something? Did you deal with CORS somewhere?

thank you

**Comment by KenavR** [comment]
Looks like it is an issue with the latest version of `@nestjs/websockets`. If I update your project to the latest version I get the same issues. Enabling CORS 

```js
  app.enableCors({
    origin: 'http://localhost:4200',
    credentials: true,
  });
```
solves the CORS related issues, but the server doesn't seem to expose the `socket.io.js` client file. Anyway, I guess you can't help me there and I need to investigate further.

Have a nice day.

**Comment by lil12t** [comment]
This is how i solved

```ts
import { IoAdapter } from '@nestjs/platform-socket.io';

export class SocketAdapter extends IoAdapter {
  createIOServer(port: number, options?: any): any {
    const server = super.createIOServer(port, { ...options, cors: true });
    return server;
  }
}
```

main.ts
```tsx
app.useWebSocketAdapter(new SocketAdapter(app));
```

**Comment by Shadow0143** [comment]
Thanks lil12t  

this is very help ful for me..

**Comment by lil12t** [comment]
> Thanks lil12t  
> 
> 
> 
> this is very help ful for me..
> 
> 

[Here](https://stackoverflow.com/a/68636839/14087063) is a better fix
